# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - sssssssssssss03

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkstyle-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      
      - name: Run Checkstyle
        run: mvn checkstyle:check
        
      - name: Build project with Maven
        run: mvn clean install --file pom.xml
        
      - name: Dependency Test
        run: mvn dependency:analyze
        
      - name: Run Tests with Code Coverage
        run: mvn test jacoco:report

      - name: Generate JaCoCo badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
         badges-directory: badges
         generate-branches-badge: true
         generate-summary: true

      - name: Log coverage percentages to workflow output
        run: |
         echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
         echo "branches = ${{ steps.jacoco.outputs.branches }}"
      - name: Upload JaCoCo coverage report as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
         name: jacoco-report
         path: target/site/jacoco/




      - name: Get the Coverage info
        run: |
         echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
         echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
          
