name: Java App Service CI/CD

on:
  push:
    branches:
      - main


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project with Maven
        run: mvn clean install --file pom.xml
        
      - name: Dependency Test
        run: mvn dependency:analyze
        
      - name: Run Tests with Code Coverage
        run: mvn test jacoco:report

  report:
     name: Upload JaCoCo Report
     needs: build_and_test
     runs-on: ubuntu-latest
     if: always()

     steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Archive JaCoCo Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html
